[package.create]
max_package_size = 1000000000

[package.create.set]
# renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
bigbang_version = "1.54.0"