name: install-tools
description: "Install pipeline tools"

runs:
  using: composite
  steps:
    - name: Install Deps
      run: |
        apt update && apt install -y jq curl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
