resources:
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base?ref=tags/${ZARF_VAR_BIGBANG_VERSION}

configMapGenerator:
  - name: common
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml
