apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bigbang
  namespace: flux-system
spec:
  interval: 5m
  path: "./kustomizations"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-package-big-bang
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: bigbang
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: istio-operator
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: istio
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: kyverno
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: jaeger
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: kiali
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: loki
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: promtail
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: monitoring
        #- apiVersion: helm.toolkit.fluxcd.io/v2beta1
        #  kind: HelmRelease
        #  namespace: bigbang
        #  name: neuvector
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: minio-operator
  timeout: 15m
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
