---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: bigbang
  name: bigbang
---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: zarf-package-big-bang
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/defenseunicorns/zarf-package-big-bang.git
  ref:
    tag: 1.53.0
  secretRef:
    name: private-git-server
