name: Run e2e test

on:
  schedule:
  - cron: 0 0 * * *

jobs:
  k3s-e2e:
    name: "Run e2e test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pipeline tools
        uses: ./.github/actions/install-tools

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.22.2

      - name: Create the package
        run: make build

      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: Run e2e
        run: make test
